name: README build
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch: # Allows manual triggering via API
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Get Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Configure pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/cache/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install dependencies
        run: python -m pip install -r cache/requirements.txt
      - name: Update README file
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: python today.py --incremental-update
      - name: Commit
        run: |-
          git add .
          git config --global user.email "github-actions-bot@ktauchathuranga.github.io"
          git config --global user.name "ktauchathuranga/GitHub-Actions-Bot"
          git commit -m "Updated README" -a || echo "No changes to commit"
          git pull --rebase # Pull the changes from the remote repository with rebase to avoid merge conflicts
          git push
